// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PingAPIOKCode is the HTTP code returned for type PingAPIOK
const PingAPIOKCode int = 200

/*
PingAPIOK OK message.

swagger:response pingApiOK
*/
type PingAPIOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPingAPIOK creates PingAPIOK with default headers values
func NewPingAPIOK() *PingAPIOK {

	return &PingAPIOK{}
}

// WithPayload adds the payload to the ping Api o k response
func (o *PingAPIOK) WithPayload(payload string) *PingAPIOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ping Api o k response
func (o *PingAPIOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PingAPIOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
